### ISSUE TITLE
Support for YOLO v8?

### ISSUE THREAD

**Issue by KhoaVo** [Hyuto/yolov5-tfjs#5]
Hi,

Do you think this repo as well as your [segmentation repo](https://github.com/Hyuto/yolov5-seg-onnxruntime-web)

Will support the latest YOLO v8 model for detection and segmentation?
https://github.com/ultralytics/ultralytics

It seems you can already export it to ONNX
https://docs.ultralytics.com/tasks/detection/
https://docs.ultralytics.com/tasks/segmentation/

Then we could use something like
https://github.com/onnx/onnx-tensorflow to get it to tfjs if needed

I wonder if it's just plug and play if we just load the v8 model instead of the v5

**Comment by Hyuto** [comment]
Hello, this repo and my segmentation repo there is specifically for YOLOv5 models. Since YOLOv5 is relatively new and as far as I know there's a little bit difference on the last layer. So I think to combining that into this repo isn't really good idea. 

I am planning to create new repo for YOLOv8 in short of time.

**Comment by Hyuto** [comment]
Hello, just a little update here. I've create YOLOv8 Object Detection app using `onnxruntime-web` you can take a look here [yolov8-onnxruntime-web](https://github.com/Hyuto/yolov8-onnxruntime-web). 

Since YOLOv8 doesn't support `tfjs` yet an `onnxruntime-web` implementation seems to be good starter for YOLOv8 on web. Although there is something like [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) to convert onnx to tf, but I think it's best to wait an official release for tf models. 

I'm closing this issue, for YOLOv8 topics you can open issue on my new repo there.
